### ISSUE TITLE
Settlers Replay View Open Points

### ISSUE THREAD

**Issue by leRoe93** [VISAB-ORG/VISAB#111]
Hey everyone, the settlers replay view works perfectly fine and is usable. 
However there are still two "little" things that should be addressed or handled in some way:

- The replay view currently is not able to support the live mode correctly, because it initializes all its map children elements on basis of the last statistics entry in the respective `SettlersFile `object
  - I experienced with the replay view and I found this one was the optimal solution with regard to the performance
  - If the elements get replaced on every turn, the updates take too long and the frame slider jumps, stage gets irresponsive etc.
- The Positioning of the map elements **is unfortunately only roughly correct** and I was not able to solve this issue until now.
  - One problem could be: E.g. roads / streets are rotated in 3 different possible ways, depending on this rotation the anchorpoint of its coords differs in across the Y axis

Further information can be obtained from [this PR.](https://github.com/VISAB-ORG/VISAB/pull/109)

If anyone wants to try and help to adjust these small things, you are welcome. Otherwise the code needs to be touched next week by me because I am not there until Monday.

Greetings!

**Comment by VocalTrance** [comment]
> The replay view currently is not able to support the live mode correctly, because it initializes all its map children elements on basis of the last statistics entry in the respective SettlersFile object.

I don't understand the issue, why can't we just take the last entry of the already existing statistics?

> The Positioning of the map elements is unfortunately only roughly correct and I was not able to solve this issue until now.

I believe that the anchor point for unity game objects is the center point instead of a corner point.

**Comment by VocalTrance** [comment]
Okay just saw 
>The tactic of using the last data entry is not compliant with the live view as of now, because the last data entry always changes in there. This could be solved with another publish-subscribe across the view and view model.

We can just use a `ObjectProperty` for the last statistics and add a listener to it in the view.
It's ofcourse gonna cost performance, to rerender this again whenever something is buillt.
If it costs to much performance, we can also just not make this live I guess.

**Comment by leRoe93** [comment]
Settlers Views just open a dialog window indicating that live support is not fully there, this is done now.
